name: RPi Image Modifier
description: Raspberry Pi OS Image Modifier

inputs:
  base-image-url:
    description: 'Base Raspberry Pi OS image URL'
    required: true
  script-path:
    description: 'Path of script to run to modify image'
    required: false
    default: ''
  run:
    description: 'Bash script containers to run to modify image'
    required: false
    default: ''
  image-path:
    description: 'Where to locate the modifier image (default: rpi-os-modified.img)'
    required: false
    default: 'rpi-os-modified.img'
  mount-repository:
    description: 'Temporary mount repository at /mounted-github-repo/ for copying files'
    required: false
    default: 'true'
  shell:
    description: 'Shell in container to execute script (default: /bin/bash)'
    required: false
    default: '/bin/bash'
  image-maxsize:
    description: 'That maximum size of the modified image (needs to fit on disk)'
    required: false
    default: '12G'

outputs:
  image-path:
    description: 'Path of modified Raspberry Pi OS image'
    #value: ${{ steps.random-number-generator.outputs.random-number }}
    value: TODO

runs:
  using: "composite"
  steps:
    -
      name: Modify Raspberry Pi OS image
      shell: bash
      id: download-image
      env:
        ARG_BASE_IMAGE_URL: ${{ inputs.base-image-url }}
        ARG_SCRIPT_PATH: ${{ inputs.script-path }}
        ARG_RUN: ${{ inputs.run }}
        ARG_IMAGE_PATH: ${{ inputs.image-path }}
        ARG_MOUNT_REPOSITORY: ${{ inputs.mount-repository == 'true' && '1' || '' }}
        ARG_SHELL: ${{ inputs.shell }}
        ARG_IMAGE_MAXSIZE: ${{ inputs.image-maxsize }}
      run:  "${GITHUB_ACTION_PATH}/action.sh"
    -
      name: Debug
      uses: mxschmitt/action-tmate@v3
