name: RPi Image Modifier
description: Raspberry Pi OS Image Modifier

inputs:
  base-image-url:
    description: 'Base Raspberry Pi OS image URL'
    required: true
  image-path:
    description: 'Where to locate the modifier image'
    required: false
    default: ''
  files:
    description: 'Files to copy to image'
    required: false
    default: ''
  script-path:
    description: 'Path of script to run to modify image'
    required: false
    default: ''
  run:
    description: 'Bash script containers to run to modify image'
    required: false
    default: ''
  image-maxsize:
    description: 'That maximum size of the modified image'
    required: false
    default: '12G'

outputs:
  image-path:
    description: 'Path of modified Raspberry Pi OS image'
    #value: ${{ steps.random-number-generator.outputs.random-number }}
    value: TODO

runs:
  using: "composite"
  steps:
    -
      name: Make sure environment is supported
      shell: bash
      env:
        ARG_SCRIPT_PATH: ${{ inputs.script-path }}
        ARG_RUN: ${{ inputs.run }}
      run: |
        if [ "${RUNNER_OS}" != "Linux" ]; then
          echo "${RUNNER_OS} not supported"
          exit 1
        fi

        if [ -z "${ARG_SCRIPT_PATH}" -a -z "${ARG_RUN}" ]; then
          echo 'You must specify either a script-path or run input'
          exit 1
        fi
    -
      name: Setup requirements
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          qemu-user-static \
          systemd-container
        sudo wget -O /usr/local/bin/pishrink.sh https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
        sudo chmod +x /usr/local/bin/pishrink.sh
    -
      name: Modify Raspberry Pi OS image
      shell: bash
      id: download-image
      env:
        ARG_BASE_IMAGE_URL: ${{ inputs.base-image-url }}
        ARG_IMAGE_PATH: ${{ inputs.image-path }}
        ARG_FILES: ${{ inputs.files }}
        ARG_SCRIPT_PATH: ${{ inputs.script-path }}
        ARG_RUN: ${{ inputs.run }}
        ARG_IMAGE_MAXSIZE: ${{ inputs.image-maxsize }}
      run:  "${GITHUB_ACTION_PATH}/action.sh"
    -
      name: Debug
      uses: mxschmitt/action-tmate@v3
