name: Test action

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test action
        uses: ./
        with:
          base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-06/2023-12-05-raspios-bookworm-arm64-lite.img.xz
          run: |
            echo 'hi mom'
